discord_key: ''
discord_admin_username: ''
debug_channel_id: ''
reddit_id: ''
reddit_user_agent: ''
reddit_secret: ''
anime_reddit_username: ''
anime_channel_id: ''
star_citizen_reddit_username: ''
star_citizen_channel_id: ''